### ISSUE TITLE
Locations in the location drop down on /location_interests/new could use better sorting.

### ISSUE THREAD

**Issue by trayo** [turingschool/people#31]
Currently it almost seems like locations are sorted randomly if you delete a location and then add it back to your profile.

Solution: Sort locations alphabetically by state and then city name. Some of the locations aren't actually locations (ex: `remote`, `willing to move for the right opportunity`) and these should be placed at the beginning or end of the list.

**Comment by jcasimir** [comment]
Agreed. Can you make a PR?
